workflows:
  android-uber-build:
    name: Uber Passenger Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - firebase_credentials
      vars:
        PACKAGE_NAME: "com.example.uberuser"
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:

      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Install Dependencies
        script: |
          flutter pub get
      - name: Flutter Clean
        script: |
          flutter clean
      - name: Build Android APK
        script: |
          flutter build apk --release --build-name=1.0.${BUILD_NUMBER} --build-number=${BUILD_NUMBER} --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
