workflows:
  android-uber-build:
    name: Uber Passenger Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - firebase_credentials
      vars:
        PACKAGE_NAME: "com.fredjrp.uberpassenger"
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Set up Firebase Config
        script: | 
          echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Force Modern Dependencies
        script: |
          # This handles the 'intl' and other library version clashes
          flutter pub upgrade --major-versions
      - name: Flutter Clean
        script: |
          flutter clean
      - name: Build Android APK
        script: |
          # Build without the legacy null-safety flag
          flutter build apk --release --build-name=1.0.${BUILD_NUMBER} --build-number=${BUILD_NUMBER}
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
